### ISSUE TITLE
Debugging mail issues

### ISSUE THREAD

**Issue by dbeniamine** [SkypLabs/webprotege-dockerfile#1]
Hello,

I am using your webprotege image but I can't make it send mail using smtp.

I've set the `mail.stmp.auth`, `mail.smtp.user`, `mail.smtp.host`, `mail.smtp.port` and `mail.smtp.wp.password` in the file `mail.properties` that is correctly mounted according to the Readme.
The credentials are correct so i don't understand what is going wrong, maybe webprotege is trying to use a wrong protocol (ssl/starttls) ...

Are the mail connection logged somewhere ?

**Comment by SkypLabs** [comment]
Hi there,

Start an instance of WebProtege and check if the `mail.properties` file is well mounted using the following command:

    docker exec <container's name> cat ROOT/WEB-INF/classes/mail.properties

Normally, you should see every error message using `docker logs <container's name>`.

**Comment by SkypLabs** [comment]
@dbeniamine I'm closing this issue because I haven't heard from you in a while. Feel free to reopen it if needed.
