### ISSUE TITLE
How to bootstrap the complete setup?

### ISSUE THREAD

**Issue by ghost** [SkypLabs/webprotege-dockerfile#3]
Thank you a lot for providing this. Is there a possibility to bootstrap everything? I.e. can I spin up the service with already available projects (from source) without the need to manually configure an admin account and go into the settings page?

**Comment by SkypLabs** [comment]
Hi,

It is possible to inject a configuration file at creation time to bootstrap the service: https://github.com/SkypLabs/webprotege-dockerfile#customise-the-configuration.

I close this issue as the original author deleted their account.
